# Patches for EDA trust-manager Bundles to include Zscaler/corporate CA certificates
# This adds the zscaler-external-ca ConfigMap as a source to each Bundle

apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: eda-internal-trust-bundle
spec:
  sources:
  - secret:
      key: ca.crt
      selector:
        matchLabels:
          eda.nokia.com/ca: internal
  - configMap:
      key: shadow-trust-bundle.pem
      selector:
        matchLabels:
          eda.nokia.com/shadow-ca: internal
  - configMap:
      name: zscaler-external-ca
      key: ca-bundle.pem
---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: eda-api-trust-bundle
spec:
  sources:
  - secret:
      key: ca.crt
      selector:
        matchLabels:
          eda.nokia.com/ca: api
  - configMap:
      key: shadow-trust-bundle.pem
      selector:
        matchLabels:
          eda.nokia.com/shadow-ca: api
  - configMap:
      name: zscaler-external-ca
      key: ca-bundle.pem
---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: eda-node-trust-bundle
spec:
  sources:
  - secret:
      key: ca.crt
      selector:
        matchLabels:
          eda.nokia.com/ca: node
  - configMap:
      key: shadow-trust-bundle.pem
      selector:
        matchLabels:
          eda.nokia.com/shadow-ca: node
  - configMap:
      name: zscaler-external-ca
      key: ca-bundle.pem
